version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Toronto
    open-pull-requests-limit: 5

  - package-ecosystem: nuget
    directory: /backend
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Toronto
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /frontend/tests
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Toronto
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directories:
      - /backend
      - /frontend
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Toronto
    open-pull-requests-limit: 5

  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Toronto
    open-pull-requests-limit: 5
